# filepath: c:\Users\Klint\source\repos\SmartGrainDry\render.yml
services:
  - type: web
    name: smartgraindry
    env: docker
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 80