name: Build and Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x' # Ensure this matches the target framework

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet publish -c Release -o out

      - name: Package build artifacts
        run: tar -czvf build.tar.gz -C out .

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          mv build build.tar.gz
          curl -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -F "serviceId=SmartGrainDry" \
            -F "artifact=@build.tar.gz" \
            https://api.render.com/v1/services/SmartGrainDry/deploys